# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(738, 582)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 130, 661, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.banner_img = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.banner_img.setObjectName("banner_img")
        self.verticalLayout.addWidget(self.banner_img)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ocr_txt = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ocr_txt.setObjectName("ocr_txt")
        self.horizontalLayout.addWidget(self.ocr_txt)
        self.path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.path.setObjectName("path")
        self.horizontalLayout.addWidget(self.path)
        self.select_path = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.select_path.setObjectName("select_path")
        self.horizontalLayout.addWidget(self.select_path)
        self.start = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.banner_img.setText(_translate("Form", "banner_img"))
        self.ocr_txt.setText(_translate("Form", "识别发票"))
        self.select_path.setText(_translate("Form", "选择目录"))
        self.start.setText(_translate("Form", "开始识别"))
